import 'package:restaurant_menu_app/models/menu_item_model.dart';

// Menu Items: Burger, Pizza, Sushi, Caesar Salad, Grilled Chicken, Fish Tacos,
// Pasta Carbonara, BBQ Ribs, Vegetable Stir Fry, Chocolate Cake, French Fries,
// Greek Salad, Pad Thai, Chicken Wings, Beef Steak, Ice Cream Sundae, Quesadilla
List<MenuItemModel> menuItems = [
  MenuItemModel(
    name: 'Burger',
    description: 'A delicious beef burger with cheese and lettuce.',
    price: 5.99,
    image: 'assets/images/burger.jpg',
    category: 'Fast Food',
  ),
  MenuItemModel(
    name: 'Pizza',
    description: 'A classic pepperoni pizza with a crispy crust.',
    price: 8.99,
    image: 'assets/images/pizza.jpg',
    category: 'Italian',
  ),
  MenuItemModel(
    name: 'Sushi',
    description: 'Fresh sushi rolls with salmon and avocado.',
    price: 12.99,
    image: 'assets/images/sushi.jpg',
    category: 'Japanese',
  ),
  MenuItemModel(
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with parmesan cheese and croutons.',
    price: 7.50,
    image: 'assets/images/caesar_salad.jpg',
    category: 'Salads',
  ),
  MenuItemModel(
    name: 'Grilled Chicken',
    description: 'Tender grilled chicken breast with herbs and spices.',
    price: 11.99,
    image: 'assets/images/grilled_chicken.jpg',
    category: 'Main Course',
  ),
  MenuItemModel(
    name: 'Fish Tacos',
    description: 'Crispy fish tacos with cabbage slaw and lime.',
    price: 9.50,
    image: 'assets/images/fish_tacos.jpg',
    category: 'Mexican',
  ),
  MenuItemModel(
    name: 'Pasta Carbonara',
    description: 'Creamy pasta with bacon, eggs, and parmesan cheese.',
    price: 10.99,
    image: 'assets/images/carbonara.jpg',
    category: 'Italian',
  ),
  MenuItemModel(
    name: 'BBQ Ribs',
    description: 'Slow-cooked ribs with smoky BBQ sauce.',
    price: 15.99,
    image: 'assets/images/bbq_ribs.jpg',
    category: 'BBQ',
  ),
  MenuItemModel(
    name: 'Vegetable Stir Fry',
    description: 'Fresh vegetables stir-fried with soy sauce and ginger.',
    price: 8.50,
    image: 'assets/images/stir_fry.jpeg',
    category: 'Asian',
  ),
  MenuItemModel(
    name: 'Chocolate Cake',
    description: 'Rich chocolate cake with creamy frosting.',
    price: 4.99,
    image: 'assets/images/chocolate_cake.jpg',
    category: 'Desserts',
  ),
  MenuItemModel(
    name: 'French Fries',
    description: 'Crispy golden fries with a side of ketchup.',
    price: 3.50,
    image: 'assets/images/french_fries.jpg',
    category: 'Sides',
  ),
  MenuItemModel(
    name: 'Greek Salad',
    description: 'Mediterranean salad with olives, feta cheese, and tomatoes.',
    price: 8.99,
    image: 'assets/images/greek_salad.jpg',
    category: 'Salads',
  ),
  MenuItemModel(
    name: 'Pad Thai',
    description: 'Traditional Thai noodles with shrimp and peanuts.',
    price: 11.50,
    image: 'assets/images/pad_thai.jpeg',
    category: 'Thai',
  ),
  MenuItemModel(
    name: 'Chicken Wings',
    description: 'Spicy buffalo wings with blue cheese dip.',
    price: 7.99,
    image: 'assets/images/chicken_wings.jpg',
    category: 'Appetizers',
  ),
  MenuItemModel(
    name: 'Beef Steak',
    description: 'Juicy grilled steak cooked to perfection.',
    price: 18.99,
    image: 'assets/images/beef_steak.jpg',
    category: 'Main Course',
  ),
  MenuItemModel(
    name: 'Ice Cream Sundae',
    description: 'Vanilla ice cream with chocolate sauce and cherry.',
    price: 5.50,
    image: 'assets/images/ice_cream.jpg',
    category: 'Desserts',
  ),
  MenuItemModel(
    name: 'Quesadilla',
    description: 'Grilled tortilla with cheese, chicken, and peppers.',
    price: 6.99,
    image: 'assets/images/quesadillas.jpg',
    category: 'Mexican',
  ),
];
